---
language: ruby
rvm:
- 1.9.3
before_script: bundle exec rake db:migrate
script: bundle exec rake test cucumber
notifications:
  email: false
  irc:
    channels:
    - ircnet.eversible.com#scrumcaptain
    use_notice: true
    skip_join: true
    template:
    - ! '----'
    - ! '%{message}'
    - ! '%{repository}/%{branch}#%{build_number} (%{author})'
    - ! 'Commit message : %{commit_message}'
    - ! 'Build details  : %{build_url}'
    - ! '----'
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:scrumboat.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrichHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
- yes | heroku run rake db:migrate
env:
  global:
    secure: ! 'YGas3XgNewWLAUJ/Y3uYR3UctzznYHxdsBFykXzoxckKxup+C7mvTQ8ZumZo

      CyIRthgzSO7dPXnRqn/AYcDRFrpPIzV7PeYVTTWLOvTcbssr3mzphNoRWM5s

      y4Q9jGecf4ntpNgd5IegkMaIouzwX6hDRcUYba9sJHFLU3UGABs='
