language: ruby
rvm:
  - 1.9.3
before_script: bundle exec rake db:migrate
script: bundle exec rake test cucumber
notifications:
  email: false
  irc:
    channels:
    - ircnet.eversible.com#scrumcaptain
    use_notice: true
    skip_join: true
    template:
    - "----"
    - "%{message}"
    - "%{repository}/%{branch}#%{build_number} (%{author})"
	- "Commit message: {commit_message}"
    - "Build details : %{build_url}"
    - "----"
