require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BerthsController do

  # This should return the minimal set of attributes required to create a valid
  # Berth. As you add validations to Berth, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BerthsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all berths as @berths" do
      berth = Berth.create! valid_attributes
      get :index, {}, valid_session
      assigns(:berths).should eq([berth])
    end
  end

  describe "GET show" do
    it "assigns the requested berth as @berth" do
      berth = Berth.create! valid_attributes
      get :show, {:id => berth.to_param}, valid_session
      assigns(:berth).should eq(berth)
    end
  end

  describe "GET new" do
    it "assigns a new berth as @berth" do
      get :new, {}, valid_session
      assigns(:berth).should be_a_new(Berth)
    end
  end

  describe "GET edit" do
    it "assigns the requested berth as @berth" do
      berth = Berth.create! valid_attributes
      get :edit, {:id => berth.to_param}, valid_session
      assigns(:berth).should eq(berth)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Berth" do
        expect {
          post :create, {:berth => valid_attributes}, valid_session
        }.to change(Berth, :count).by(1)
      end

      it "assigns a newly created berth as @berth" do
        post :create, {:berth => valid_attributes}, valid_session
        assigns(:berth).should be_a(Berth)
        assigns(:berth).should be_persisted
      end

      it "redirects to the created berth" do
        post :create, {:berth => valid_attributes}, valid_session
        response.should redirect_to(Berth.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved berth as @berth" do
        # Trigger the behavior that occurs when invalid params are submitted
        Berth.any_instance.stub(:save).and_return(false)
        post :create, {:berth => {  }}, valid_session
        assigns(:berth).should be_a_new(Berth)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Berth.any_instance.stub(:save).and_return(false)
        post :create, {:berth => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested berth" do
        berth = Berth.create! valid_attributes
        # Assuming there are no other berths in the database, this
        # specifies that the Berth created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Berth.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => berth.to_param, :berth => { "these" => "params" }}, valid_session
      end

      it "assigns the requested berth as @berth" do
        berth = Berth.create! valid_attributes
        put :update, {:id => berth.to_param, :berth => valid_attributes}, valid_session
        assigns(:berth).should eq(berth)
      end

      it "redirects to the berth" do
        berth = Berth.create! valid_attributes
        put :update, {:id => berth.to_param, :berth => valid_attributes}, valid_session
        response.should redirect_to(berth)
      end
    end

    describe "with invalid params" do
      it "assigns the berth as @berth" do
        berth = Berth.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Berth.any_instance.stub(:save).and_return(false)
        put :update, {:id => berth.to_param, :berth => {  }}, valid_session
        assigns(:berth).should eq(berth)
      end

      it "re-renders the 'edit' template" do
        berth = Berth.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Berth.any_instance.stub(:save).and_return(false)
        put :update, {:id => berth.to_param, :berth => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested berth" do
      berth = Berth.create! valid_attributes
      expect {
        delete :destroy, {:id => berth.to_param}, valid_session
      }.to change(Berth, :count).by(-1)
    end

    it "redirects to the berths list" do
      berth = Berth.create! valid_attributes
      delete :destroy, {:id => berth.to_param}, valid_session
      response.should redirect_to(berths_url)
    end
  end

end
