require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GuardseasonsController do

  # This should return the minimal set of attributes required to create a valid
  # Guardseason. As you add validations to Guardseason, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nimi" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuardseasonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all guardseasons as @guardseasons" do
      guardseason = Guardseason.create! valid_attributes
      get :index, {}, valid_session
      assigns(:guardseasons).should eq([guardseason])
    end
  end

  describe "GET show" do
    it "assigns the requested guardseason as @guardseason" do
      guardseason = Guardseason.create! valid_attributes
      get :show, {:id => guardseason.to_param}, valid_session
      assigns(:guardseason).should eq(guardseason)
    end
  end

  describe "GET new" do
    it "assigns a new guardseason as @guardseason" do
      get :new, {}, valid_session
      assigns(:guardseason).should be_a_new(Guardseason)
    end
  end

  describe "GET edit" do
    it "assigns the requested guardseason as @guardseason" do
      guardseason = Guardseason.create! valid_attributes
      get :edit, {:id => guardseason.to_param}, valid_session
      assigns(:guardseason).should eq(guardseason)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Guardseason" do
        expect {
          post :create, {:guardseason => valid_attributes}, valid_session
        }.to change(Guardseason, :count).by(1)
      end

      it "assigns a newly created guardseason as @guardseason" do
        post :create, {:guardseason => valid_attributes}, valid_session
        assigns(:guardseason).should be_a(Guardseason)
        assigns(:guardseason).should be_persisted
      end

      it "redirects to the created guardseason" do
        post :create, {:guardseason => valid_attributes}, valid_session
        response.should redirect_to(Guardseason.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved guardseason as @guardseason" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guardseason.any_instance.stub(:save).and_return(false)
        post :create, {:guardseason => { "nimi" => "invalid value" }}, valid_session
        assigns(:guardseason).should be_a_new(Guardseason)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guardseason.any_instance.stub(:save).and_return(false)
        post :create, {:guardseason => { "nimi" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested guardseason" do
        guardseason = Guardseason.create! valid_attributes
        # Assuming there are no other guardseasons in the database, this
        # specifies that the Guardseason created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Guardseason.any_instance.should_receive(:update_attributes).with({ "nimi" => "MyString" })
        put :update, {:id => guardseason.to_param, :guardseason => { "nimi" => "MyString" }}, valid_session
      end

      it "assigns the requested guardseason as @guardseason" do
        guardseason = Guardseason.create! valid_attributes
        put :update, {:id => guardseason.to_param, :guardseason => valid_attributes}, valid_session
        assigns(:guardseason).should eq(guardseason)
      end

      it "redirects to the guardseason" do
        guardseason = Guardseason.create! valid_attributes
        put :update, {:id => guardseason.to_param, :guardseason => valid_attributes}, valid_session
        response.should redirect_to(guardseason)
      end
    end

    describe "with invalid params" do
      it "assigns the guardseason as @guardseason" do
        guardseason = Guardseason.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guardseason.any_instance.stub(:save).and_return(false)
        put :update, {:id => guardseason.to_param, :guardseason => { "nimi" => "invalid value" }}, valid_session
        assigns(:guardseason).should eq(guardseason)
      end

      it "re-renders the 'edit' template" do
        guardseason = Guardseason.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guardseason.any_instance.stub(:save).and_return(false)
        put :update, {:id => guardseason.to_param, :guardseason => { "nimi" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested guardseason" do
      guardseason = Guardseason.create! valid_attributes
      expect {
        delete :destroy, {:id => guardseason.to_param}, valid_session
      }.to change(Guardseason, :count).by(-1)
    end

    it "redirects to the guardseasons list" do
      guardseason = Guardseason.create! valid_attributes
      delete :destroy, {:id => guardseason.to_param}, valid_session
      response.should redirect_to(guardseasons_url)
    end
  end

end
