require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PricingsController do

  # This should return the minimal set of attributes required to create a valid
  # Pricing. As you add validations to Pricing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "target" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PricingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pricings as @pricings" do
      pricing = Pricing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pricings).should eq([pricing])
    end
  end

  describe "GET show" do
    it "assigns the requested pricing as @pricing" do
      pricing = Pricing.create! valid_attributes
      get :show, {:id => pricing.to_param}, valid_session
      assigns(:pricing).should eq(pricing)
    end
  end

  describe "GET new" do
    it "assigns a new pricing as @pricing" do
      get :new, {}, valid_session
      assigns(:pricing).should be_a_new(Pricing)
    end
  end

  describe "GET edit" do
    it "assigns the requested pricing as @pricing" do
      pricing = Pricing.create! valid_attributes
      get :edit, {:id => pricing.to_param}, valid_session
      assigns(:pricing).should eq(pricing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pricing" do
        expect {
          post :create, {:pricing => valid_attributes}, valid_session
        }.to change(Pricing, :count).by(1)
      end

      it "assigns a newly created pricing as @pricing" do
        post :create, {:pricing => valid_attributes}, valid_session
        assigns(:pricing).should be_a(Pricing)
        assigns(:pricing).should be_persisted
      end

      it "redirects to the created pricing" do
        post :create, {:pricing => valid_attributes}, valid_session
        response.should redirect_to(Pricing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pricing as @pricing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pricing.any_instance.stub(:save).and_return(false)
        post :create, {:pricing => { "target" => "invalid value" }}, valid_session
        assigns(:pricing).should be_a_new(Pricing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pricing.any_instance.stub(:save).and_return(false)
        post :create, {:pricing => { "target" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pricing" do
        pricing = Pricing.create! valid_attributes
        # Assuming there are no other pricings in the database, this
        # specifies that the Pricing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pricing.any_instance.should_receive(:update_attributes).with({ "target" => "MyString" })
        put :update, {:id => pricing.to_param, :pricing => { "target" => "MyString" }}, valid_session
      end

      it "assigns the requested pricing as @pricing" do
        pricing = Pricing.create! valid_attributes
        put :update, {:id => pricing.to_param, :pricing => valid_attributes}, valid_session
        assigns(:pricing).should eq(pricing)
      end

      it "redirects to the pricing" do
        pricing = Pricing.create! valid_attributes
        put :update, {:id => pricing.to_param, :pricing => valid_attributes}, valid_session
        response.should redirect_to(pricing)
      end
    end

    describe "with invalid params" do
      it "assigns the pricing as @pricing" do
        pricing = Pricing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pricing.any_instance.stub(:save).and_return(false)
        put :update, {:id => pricing.to_param, :pricing => { "target" => "invalid value" }}, valid_session
        assigns(:pricing).should eq(pricing)
      end

      it "re-renders the 'edit' template" do
        pricing = Pricing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pricing.any_instance.stub(:save).and_return(false)
        put :update, {:id => pricing.to_param, :pricing => { "target" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pricing" do
      pricing = Pricing.create! valid_attributes
      expect {
        delete :destroy, {:id => pricing.to_param}, valid_session
      }.to change(Pricing, :count).by(-1)
    end

    it "redirects to the pricings list" do
      pricing = Pricing.create! valid_attributes
      delete :destroy, {:id => pricing.to_param}, valid_session
      response.should redirect_to(pricings_url)
    end
  end

end
